on: 
  push:
    branches:
    -  main 
name: build and push docker
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: octocat/curso
        ref: v1.0
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
